all:
	gcc -Wall -fPIC -c m_login.cpp
	gcc -shared -o m_login.so m_login.o
	gcc -Wall -fPIC -c m_register.cpp
	gcc -shared -o m_register.so m_register.o
	gcc -Wall -fPIC -c m_delete.cpp
	gcc -shared -o m_delete.so m_delete.o
